---
- name: Restart SSH service on all hosts
  hosts: all  # 여기에 'hosts'를 정확히 사용
  become: yes  # sudo 권한을 사용하려면 'become: yes' 추가
  tasks:
    - name: restart sshd service
      ansible.builtin.service:
        name: sshd
        state: restarted

