---

- hosts: all
  vars_files:
    - vars/secret.yaml
  tasks:
  - name: Create user
    ansible.builtin.user:
      name: "{{ item.userid }}"
      password: "{{ item.userpw | password_hash('sha512') }}"
      state: present
    with_items: "{{ user_info }}"
  