---

- hosts: all
  vars:
    supported_distros:
      - Rocky
      - CentOS

  tasks:
    - name: Print supported OS
      ansible.builtin.debug:
        msg: "this {{ansible_facts['distribution']}} is supported need to use dnf"
      when: ansible_facts['distribution'] in supported_distros
